CREATE DATABASE WEST_BANK;

USE WEST_BANK;

CREATE TABLE CLIENTE(
	RUT VARCHAR(12) NOT NULL,
	NOMBRE VARCHAR(25) NOT NULL,
	APELLIDO_PATERNO VARCHAR(25) NOT NULL,
    APELLIDO_MATERNO VARCHAR(25),
    DOMICILIO VARCHAR(50) NOT NULL,
    COMUNA VARCHAR(15) NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    NUMERO_CUENTA INT(9) NOT NULL,
    UNIQUE(RUT),
    CONSTRAINT PK_CLIENTE PRIMARY KEY(RUT),
    CONSTRAINT FK_CUENTA1 FOREIGN KEY (NUMERO_CUENTA) REFERENCES cuenta(NUMERO_CUENTA));
    
CREATE TABLE CUENTA(
	NUMERO_CUENTA INT(9) NOT NULL,
	TIPO_CUENTA VARCHAR(20) NOT NULL, 
	SALDO INT(10),
    UNIQUE(NUMERO_CUENTA),
    CONSTRAINT PK_CUENTA PRIMARY KEY(NUMERO_CUENTA)
);
