package bank.gestionarCuenta;

import bank.classBank.Cliente;
import bank.functions.FuncionesMenu;
import javax.swing.JOptionPane;
import bank.functions.funcionesBanco;
import java.util.ArrayList;

public class gestionarCuenta extends javax.swing.JFrame {
    String rut = new String();
    String monto = new String();
    ArrayList<Cliente> clienteBanco;
    FuncionesMenu menu = new FuncionesMenu();

    public gestionarCuenta(ArrayList<Cliente> clienteBanco) {
        this.clienteBanco = clienteBanco;
        initComponents();
        
        jp_depositar.setVisible(false);
        jp_girar.setVisible(false);
        jp_transferencia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_depositar = new javax.swing.JButton();
        btn_girar = new javax.swing.JButton();
        btn_transferir = new javax.swing.JButton();
        btn_inicio = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jp_depositar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_ingreso_rut = new javax.swing.JLabel();
        txt_ingreso_rut = new javax.swing.JTextField();
        btn_validar_rut = new javax.swing.JButton();
        jp_datos_deposito = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_numeroCuenta = new javax.swing.JLabel();
        lb_tipoCuenta = new javax.swing.JLabel();
        lb_saldo_cuenta = new javax.swing.JLabel();
        jp_datos_monto_dep = new javax.swing.JPanel();
        lb_saldo_deposito = new javax.swing.JLabel();
        txt_saldo_deposito = new javax.swing.JTextField();
        btn_hacer_deposito = new javax.swing.JButton();
        jp_girar = new javax.swing.JPanel();
        jp_datos_cliente_giro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_numero_cuenta_giro = new javax.swing.JLabel();
        lb_tipoCuenta_giro = new javax.swing.JLabel();
        lb_saldoDisponible_giro = new javax.swing.JLabel();
        jp_saldo_giro = new javax.swing.JPanel();
        lb_saldo_giro = new javax.swing.JLabel();
        txt_saldo_giro = new javax.swing.JTextField();
        btn_hacer_giro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb_ingrese_rut1 = new javax.swing.JLabel();
        txt_ingreso_rut_giro = new javax.swing.JTextField();
        btn_validar_rut1 = new javax.swing.JButton();
        jp_transferencia = new javax.swing.JPanel();
        jp_datos_transferencia = new javax.swing.JPanel();
        lb_num_cuenta_origen = new javax.swing.JLabel();
        lb_num_cuenta_destino = new javax.swing.JLabel();
        txt_num_cuenta_origen = new javax.swing.JTextField();
        txt_num_cuenta_destino = new javax.swing.JTextField();
        btn_validar_cuenta = new javax.swing.JButton();
        jp_transferencia_monto = new javax.swing.JPanel();
        lb_monto_transferencia = new javax.swing.JLabel();
        txt_monto_transferencia = new javax.swing.JTextField();
        btn_hacer_transferencia = new javax.swing.JButton();
        btn_nueva_transferencia = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 523));

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(234, 84));

        btn_depositar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/deposito.png"))); // NOI18N
        btn_depositar.setText("Depositar");
        btn_depositar.setFocusable(false);
        btn_depositar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_depositar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depositarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_depositar);

        btn_girar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/giro.png"))); // NOI18N
        btn_girar.setText("        Girar        ");
        btn_girar.setFocusable(false);
        btn_girar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_girar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_girar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_girar);

        btn_transferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/transferir.png"))); // NOI18N
        btn_transferir.setText("      Transferir     ");
        btn_transferir.setFocusable(false);
        btn_transferir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_transferir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transferirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_transferir);

        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/home.png"))); // NOI18N
        btn_inicio.setText("        Inicio        ");
        btn_inicio.setFocusable(false);
        btn_inicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_inicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_inicio);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/exit.png"))); // NOI18N
        btn_salir.setText("        Salir        ");
        btn_salir.setFocusable(false);
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_salir);

        lb_ingreso_rut.setText("Ingrese rut de usuario sin punto ni guiones");

        txt_ingreso_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ingreso_rutActionPerformed(evt);
            }
        });

        btn_validar_rut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/search.png"))); // NOI18N
        btn_validar_rut.setText("Validar RUT");
        btn_validar_rut.setPreferredSize(new java.awt.Dimension(122, 32));
        btn_validar_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validar_rutActionPerformed(evt);
            }
        });

        jp_datos_deposito.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Numero cuenta");

        jLabel2.setText("Tipo de cuenta");

        jLabel3.setText("Saldo disponible");

        jLabel4.setText("Datos Cliente");

        javax.swing.GroupLayout jp_datos_depositoLayout = new javax.swing.GroupLayout(jp_datos_deposito);
        jp_datos_deposito.setLayout(jp_datos_depositoLayout);
        jp_datos_depositoLayout.setHorizontalGroup(
            jp_datos_depositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datos_depositoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_datos_depositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jp_datos_depositoLayout.createSequentialGroup()
                        .addGroup(jp_datos_depositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(jp_datos_depositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_numeroCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_tipoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_saldo_cuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jp_datos_depositoLayout.setVerticalGroup(
            jp_datos_depositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datos_depositoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jp_datos_depositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_numeroCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_datos_depositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_tipoCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_datos_depositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_saldo_cuenta))
                .addGap(31, 31, 31))
        );

        jp_datos_monto_dep.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_saldo_deposito.setText("Saldo a Depositar:");

        txt_saldo_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_saldo_depositoActionPerformed(evt);
            }
        });

        btn_hacer_deposito.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_hacer_deposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/insert_cash.png"))); // NOI18N
        btn_hacer_deposito.setText("Hacer Depósito");
        btn_hacer_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hacer_depositoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_datos_monto_depLayout = new javax.swing.GroupLayout(jp_datos_monto_dep);
        jp_datos_monto_dep.setLayout(jp_datos_monto_depLayout);
        jp_datos_monto_depLayout.setHorizontalGroup(
            jp_datos_monto_depLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datos_monto_depLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_datos_monto_depLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_saldo_deposito)
                    .addComponent(txt_saldo_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datos_monto_depLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_hacer_deposito)
                .addGap(24, 24, 24))
        );
        jp_datos_monto_depLayout.setVerticalGroup(
            jp_datos_monto_depLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datos_monto_depLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_saldo_deposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_saldo_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_hacer_deposito)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jp_datos_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp_datos_monto_dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_ingreso_rut)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_ingreso_rut, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_validar_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lb_ingreso_rut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ingreso_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_validar_rut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_datos_monto_dep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_datos_deposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jp_depositarLayout = new javax.swing.GroupLayout(jp_depositar);
        jp_depositar.setLayout(jp_depositarLayout);
        jp_depositarLayout.setHorizontalGroup(
            jp_depositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_depositarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jp_depositarLayout.setVerticalGroup(
            jp_depositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_depositarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jp_datos_cliente_giro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Datos Cliente");

        jLabel6.setText("Numero cuenta");

        jLabel7.setText("Tipo de cuenta");

        jLabel8.setText("Saldo disponible");

        javax.swing.GroupLayout jp_datos_cliente_giroLayout = new javax.swing.GroupLayout(jp_datos_cliente_giro);
        jp_datos_cliente_giro.setLayout(jp_datos_cliente_giroLayout);
        jp_datos_cliente_giroLayout.setHorizontalGroup(
            jp_datos_cliente_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datos_cliente_giroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_datos_cliente_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_datos_cliente_giroLayout.createSequentialGroup()
                        .addGroup(jp_datos_cliente_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(50, 50, 50)
                        .addGroup(jp_datos_cliente_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_numero_cuenta_giro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_tipoCuenta_giro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_saldoDisponible_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jp_datos_cliente_giroLayout.setVerticalGroup(
            jp_datos_cliente_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datos_cliente_giroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(jp_datos_cliente_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lb_numero_cuenta_giro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_datos_cliente_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lb_tipoCuenta_giro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_datos_cliente_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lb_saldoDisponible_giro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_saldo_giro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_saldo_giro.setText("Saldo a Girar:");

        txt_saldo_giro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_saldo_giroActionPerformed(evt);
            }
        });

        btn_hacer_giro.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_hacer_giro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/girar.png"))); // NOI18N
        btn_hacer_giro.setText("Hacer Giro");
        btn_hacer_giro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hacer_giroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_saldo_giroLayout = new javax.swing.GroupLayout(jp_saldo_giro);
        jp_saldo_giro.setLayout(jp_saldo_giroLayout);
        jp_saldo_giroLayout.setHorizontalGroup(
            jp_saldo_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_saldo_giroLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(btn_hacer_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jp_saldo_giroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_saldo_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_saldo_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_saldo_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_saldo_giroLayout.setVerticalGroup(
            jp_saldo_giroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_saldo_giroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lb_saldo_giro)
                .addGap(18, 18, 18)
                .addComponent(txt_saldo_giro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btn_hacer_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lb_ingrese_rut1.setText("Ingrese rut de usuario sin punto ni guiones");

        btn_validar_rut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/search.png"))); // NOI18N
        btn_validar_rut1.setText("Validar RUT");
        btn_validar_rut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validar_rut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_ingreso_rut_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_validar_rut1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_ingrese_rut1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_ingrese_rut1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ingreso_rut_giro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_validar_rut1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_girarLayout = new javax.swing.GroupLayout(jp_girar);
        jp_girar.setLayout(jp_girarLayout);
        jp_girarLayout.setHorizontalGroup(
            jp_girarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_girarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_datos_cliente_giro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_saldo_giro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_girarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_girarLayout.setVerticalGroup(
            jp_girarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_girarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_girarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_saldo_giro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_datos_cliente_giro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jp_transferencia.setPreferredSize(new java.awt.Dimension(747, 294));

        jp_datos_transferencia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_num_cuenta_origen.setText("Ingrese Número Cuenta Origen");

        lb_num_cuenta_destino.setText("Ingrese Número Cuenta Destino");

        txt_num_cuenta_origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num_cuenta_origenActionPerformed(evt);
            }
        });
        txt_num_cuenta_origen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_num_cuenta_origenKeyTyped(evt);
            }
        });

        txt_num_cuenta_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num_cuenta_destinoActionPerformed(evt);
            }
        });

        btn_validar_cuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/finalizar.png"))); // NOI18N
        btn_validar_cuenta.setText("Validar datos ingresados");
        btn_validar_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validar_cuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_datos_transferenciaLayout = new javax.swing.GroupLayout(jp_datos_transferencia);
        jp_datos_transferencia.setLayout(jp_datos_transferenciaLayout);
        jp_datos_transferenciaLayout.setHorizontalGroup(
            jp_datos_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datos_transferenciaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jp_datos_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_num_cuenta_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_num_cuenta_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num_cuenta_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_datos_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_validar_cuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_num_cuenta_destino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jp_datos_transferenciaLayout.setVerticalGroup(
            jp_datos_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datos_transferenciaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lb_num_cuenta_origen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_num_cuenta_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lb_num_cuenta_destino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_num_cuenta_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_validar_cuenta)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jp_transferencia_monto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_monto_transferencia.setText("Ingrese Monto a Transferir");

        btn_hacer_transferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/transfer.png"))); // NOI18N
        btn_hacer_transferencia.setText("Transferir");
        btn_hacer_transferencia.setPreferredSize(new java.awt.Dimension(89, 23));
        btn_hacer_transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hacer_transferenciaActionPerformed(evt);
            }
        });

        btn_nueva_transferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/img/novo.png"))); // NOI18N
        btn_nueva_transferencia.setText("Nueva Transferencia");
        btn_nueva_transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nueva_transferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_transferencia_montoLayout = new javax.swing.GroupLayout(jp_transferencia_monto);
        jp_transferencia_monto.setLayout(jp_transferencia_montoLayout);
        jp_transferencia_montoLayout.setHorizontalGroup(
            jp_transferencia_montoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_transferencia_montoLayout.createSequentialGroup()
                .addGroup(jp_transferencia_montoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_transferencia_montoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btn_nueva_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hacer_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_transferencia_montoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_transferencia_montoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_monto_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_monto_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jp_transferencia_montoLayout.setVerticalGroup(
            jp_transferencia_montoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_transferencia_montoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lb_monto_transferencia)
                .addGap(18, 18, 18)
                .addComponent(txt_monto_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_transferencia_montoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hacer_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nueva_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jp_transferenciaLayout = new javax.swing.GroupLayout(jp_transferencia);
        jp_transferencia.setLayout(jp_transferenciaLayout);
        jp_transferenciaLayout.setHorizontalGroup(
            jp_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_transferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_datos_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_transferencia_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_transferenciaLayout.setVerticalGroup(
            jp_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_transferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jp_transferencia_monto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_datos_transferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jp_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 757, Short.MAX_VALUE)
                        .addComponent(jp_depositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jp_girar, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_depositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_girar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_depositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depositarActionPerformed
        jp_depositar.setVisible(true);
        jp_girar.setVisible(false);
        jp_transferencia.setVisible(false);
        jp_datos_deposito.setVisible(false);
        jp_datos_monto_dep.setVisible(false);
    }//GEN-LAST:event_btn_depositarActionPerformed

    private void txt_ingreso_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ingreso_rutActionPerformed
        if(txt_ingreso_rut.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese rut para validación", "Advertencia", JOptionPane.OK_OPTION);
            txt_ingreso_rut.setEnabled(true);
        }
        else{
            if(funcionesBanco.isNumeric(txt_ingreso_rut.getText())){
                if(txt_ingreso_rut.getText().length() < 8 || txt_ingreso_rut.getText().length() > 9){
                    JOptionPane.showMessageDialog(null, "Ingresar rut valido sin puntos ni guiones", "Advertencia", JOptionPane.OK_OPTION);
                    txt_ingreso_rut.setEnabled(true);
                }
                else{
                    rut = funcionesBanco.checkRut(txt_ingreso_rut.getText());
                    txt_ingreso_rut.setEnabled(false);
                }   
            }
            else{
                JOptionPane.showMessageDialog(null, "Ingresar valor numerico, recuerde que el rut debe ir sin puntos ni guiones", "Advertencia", JOptionPane.OK_OPTION);
                txt_ingreso_rut.setEnabled(true);
            }
        }
    }//GEN-LAST:event_txt_ingreso_rutActionPerformed

    private void txt_saldo_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_saldo_depositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_saldo_depositoActionPerformed

    private void btn_hacer_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hacer_depositoActionPerformed
            monto = txt_saldo_deposito.getText();
            int montoInt = Integer.parseInt(monto);

            if(monto.isEmpty()){
                JOptionPane.showMessageDialog(null, "Ingresar monto", "Advertencia", JOptionPane.OK_OPTION);
            }
            else{
                for(int i = 0;i<=clienteBanco.size();i++){
                    if(clienteBanco.get(i).getRut().equals(rut)){
                        if(funcionesBanco.isNumeric(monto)){
                            if(montoInt < 0 || montoInt == 0 || monto.isEmpty()){
                                JOptionPane.showMessageDialog(null, "Ingresar monto superior a 0", "Advertencia", JOptionPane.OK_OPTION);
                            }else{
                                int nsaldo = clienteBanco.get(i).getCuenta().getSaldo() + Integer.parseInt(monto);
                                clienteBanco.get(i).getCuenta().setSaldo(nsaldo);
                                JOptionPane.showMessageDialog(null, "Deposito realizado con exito, su nuevo saldo es: "+ nsaldo, "Completado", JOptionPane.INFORMATION_MESSAGE);
                                lb_numeroCuenta.setText("");
                                lb_tipoCuenta.setText("");
                                lb_saldo_cuenta.setText("");
                                jp_datos_deposito.setVisible(false);
                                jp_datos_monto_dep.setVisible(false);
                                txt_ingreso_rut.setEnabled(true);
                                txt_ingreso_rut.setText("");
                                txt_saldo_deposito.setText("");
                                break;
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Ingresar monto numerico", "Advertencia", JOptionPane.OK_OPTION);
                            break;
                        }
                    }
                }
            }
    }//GEN-LAST:event_btn_hacer_depositoActionPerformed

    private void txt_saldo_giroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_saldo_giroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_saldo_giroActionPerformed

    private void btn_hacer_giroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hacer_giroActionPerformed
        monto = txt_saldo_deposito.getText();
        int montoInt = Integer.parseInt(monto);

        if(monto.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar monto", "Advertencia", JOptionPane.OK_OPTION);
        }
        else{
            for(int i = 0;i<=clienteBanco.size();i++){
                if(clienteBanco.get(i).getRut().equals(rut)){
                    if(funcionesBanco.isNumeric(monto)){
                        if(montoInt < 0 || montoInt == 0 || monto.isEmpty()){
                            JOptionPane.showMessageDialog(null, "Ingresar monto superior a 0", "Advertencia", JOptionPane.OK_OPTION);
                        }else{
                            int nsaldo = clienteBanco.get(i).getCuenta().getSaldo() - Integer.parseInt(monto);
                            clienteBanco.get(i).getCuenta().setSaldo(nsaldo);
                            JOptionPane.showMessageDialog(null, "Giro realizado con exito, su nuevo saldo es: " + nsaldo, "Completado", JOptionPane.INFORMATION_MESSAGE);
                            lb_numeroCuenta.setText("");
                            lb_tipoCuenta.setText("");
                            lb_saldo_cuenta.setText("");
                            jp_datos_deposito.setVisible(false);
                            jp_datos_monto_dep.setVisible(false);
                            txt_ingreso_rut.setEnabled(true);
                            txt_ingreso_rut.setText("");
                            txt_saldo_giro.setText("");
                            break;
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Ingresar monto numerico", "Advertencia", JOptionPane.OK_OPTION);
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_btn_hacer_giroActionPerformed

    private void btn_girarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girarActionPerformed
        jp_depositar.setVisible(false);
        jp_girar.setVisible(true);
        jp_transferencia.setVisible(false);
        jp_datos_cliente_giro.setVisible(false);
        jp_saldo_giro.setVisible(false);
    }//GEN-LAST:event_btn_girarActionPerformed

    private void btn_transferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transferirActionPerformed
        jp_depositar.setVisible(false);
        jp_girar.setVisible(false);
        jp_transferencia.setVisible(true);
        jp_transferencia_monto.setVisible(false);
    }//GEN-LAST:event_btn_transferirActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        menu.home(clienteBanco);
        this.dispose();
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_validar_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validar_rutActionPerformed
        if(txt_ingreso_rut.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese rut para validacion", "Advertencia", JOptionPane.OK_OPTION);
            txt_ingreso_rut.setEnabled(true);
        }
        else{
            if(funcionesBanco.isNumeric(txt_ingreso_rut.getText())){
                if(txt_ingreso_rut.getText().length() < 8 || txt_ingreso_rut.getText().length() > 9){
                    JOptionPane.showMessageDialog(null, "Ingresar rut valido sin puntos ni guiones", "Advertencia", JOptionPane.OK_OPTION);
                    txt_ingreso_rut.setEnabled(true);
                }
                else{
                    rut = funcionesBanco.checkRut(txt_ingreso_rut.getText());
                    if(clienteBanco == null){
                        JOptionPane.showMessageDialog(null, "rut no se registra en sistema", "Advertencia", JOptionPane.OK_OPTION);
                    }
                    else{
                        for(int i = 0;i<=clienteBanco.size();i++){
                            if(clienteBanco.size()>0){
                                if(clienteBanco.get(i).getRut().equals(rut)||clienteBanco.size()==0){
                                    lb_numeroCuenta.setText(": "+Integer.toString(clienteBanco.get(i).getCuenta().getNumeroCuenta()));
                                    lb_tipoCuenta.setText(": "+clienteBanco.get(i).getCuenta().getTipoCuenta());
                                    lb_saldo_cuenta.setText(": "+Integer.toString(clienteBanco.get(i).getCuenta().getSaldo()));
                                    jp_datos_deposito.setVisible(true);
                                    jp_datos_monto_dep.setVisible(true);
                                    txt_ingreso_rut.setEnabled(false);
                                    break;
                                }
                            }
                            else{
                                txt_ingreso_rut.setEnabled(true);
                            }
                        }
                    }
                }   
            }
            else{
                JOptionPane.showMessageDialog(null, "Ingresar valor numerico, recuerde que el rut debe ir sin puntos ni guiones", "Advertencia", JOptionPane.OK_OPTION);
                txt_ingreso_rut.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btn_validar_rutActionPerformed

    private void btn_validar_rut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validar_rut1ActionPerformed
        if(txt_ingreso_rut_giro.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese rut para validacion", "Advertencia", JOptionPane.OK_OPTION);
            txt_ingreso_rut_giro.setEnabled(true);
        }
        else{
            if(funcionesBanco.isNumeric(txt_ingreso_rut_giro.getText())){
                if(txt_ingreso_rut_giro.getText().length() < 8 || txt_ingreso_rut_giro.getText().length() > 9){
                    JOptionPane.showMessageDialog(null, "Ingresar rut valido sin puntos ni guiones", "Advertencia", JOptionPane.OK_OPTION);
                    txt_ingreso_rut_giro.setEnabled(true);
                }
                else{
                    rut = funcionesBanco.checkRut(txt_ingreso_rut_giro.getText());
                    if(clienteBanco == null){
                        JOptionPane.showMessageDialog(null, "rut no se registra en sistema", "Advertencia", JOptionPane.OK_OPTION);
                    }
                    else{
                        for(int i = 0;i<=clienteBanco.size();i++){
                            if(clienteBanco.size()>0){
                                if(clienteBanco.get(i).getRut().equals(rut)||clienteBanco.size()==0){
                                    lb_numero_cuenta_giro.setText(": "+Integer.toString(clienteBanco.get(i).getCuenta().getNumeroCuenta()));
                                    lb_tipoCuenta_giro.setText(": "+clienteBanco.get(i).getCuenta().getTipoCuenta());
                                    lb_saldo_giro.setText(": "+Integer.toString(clienteBanco.get(i).getCuenta().getSaldo()));
                                    jp_datos_cliente_giro.setVisible(true);
                                    jp_saldo_giro.setVisible(true);
                                    txt_ingreso_rut_giro.setEnabled(false);
                                    break;
                                }
                            }
                            else{
                                txt_ingreso_rut_giro.setEnabled(true);
                            }
                        }
                    }
                }   
            }
            else{
                JOptionPane.showMessageDialog(null, "Ingresar valor numerico, recuerde que el rut debe ir sin puntos ni guiones", "Advertencia", JOptionPane.OK_OPTION);
                txt_ingreso_rut_giro.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btn_validar_rut1ActionPerformed

    private void btn_nueva_transferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nueva_transferenciaActionPerformed
        jp_transferencia_monto.setVisible(false);
        txt_num_cuenta_origen.setText("");
        txt_num_cuenta_destino.setText("");
        txt_monto_transferencia.setText("");        
    }//GEN-LAST:event_btn_nueva_transferenciaActionPerformed

    private void btn_validar_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validar_cuentaActionPerformed
        if(txt_num_cuenta_origen.getText().isEmpty() || txt_num_cuenta_destino.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Complete los datos requeridos para validar", "Advertencia", JOptionPane.OK_OPTION); 
        }
        else{
            if(funcionesBanco.isNumeric(txt_num_cuenta_origen.getText()) && funcionesBanco.isNumeric(txt_num_cuenta_destino.getText())){
                int numeroCuentaOrigenInt = Integer.parseInt(txt_num_cuenta_origen.getText());
                int numeroCuentaDestinoInt = Integer.parseInt(txt_num_cuenta_origen.getText());
                if((txt_num_cuenta_origen.getText().length() == 9) && (numeroCuentaOrigenInt > 0) && (txt_num_cuenta_destino.getText().length() == 9) && (numeroCuentaDestinoInt > 0)){
                    if(funcionesBanco.verificarCuenta(clienteBanco, txt_num_cuenta_origen.getText())){
                        if(funcionesBanco.verificarCuenta(clienteBanco, txt_num_cuenta_destino.getText()) ){
                            jp_transferencia_monto.setVisible(true); 
                        }
                        else{
                           JOptionPane.showMessageDialog(null, "Cuenta de destino no se registra en sistema", "Advertencia", JOptionPane.OK_OPTION); 
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Cuenta de origen no se registra en sistema", "Advertencia", JOptionPane.OK_OPTION);
                    }  
                }
                else{
                    JOptionPane.showMessageDialog(null, "Ingrese numeros de cuentas a transferir numericos y de 9 digitos", "Advertencia", JOptionPane.OK_OPTION);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Ingrese numeros de cuentas a transferir numericos y de 9 digitos", "Advertencia", JOptionPane.OK_OPTION);
            } 
        }
    }//GEN-LAST:event_btn_validar_cuentaActionPerformed

    private void txt_num_cuenta_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num_cuenta_destinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num_cuenta_destinoActionPerformed

    private void txt_num_cuenta_origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num_cuenta_origenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num_cuenta_origenActionPerformed

    private void btn_hacer_transferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hacer_transferenciaActionPerformed
        if(txt_monto_transferencia.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar monto a transferir", "Advertencia", JOptionPane.OK_OPTION);
        }
        else{
            if(funcionesBanco.isNumeric(txt_monto_transferencia.getText())){
                int montoTransferencia = Integer.parseInt(txt_monto_transferencia.getText());
                if(montoTransferencia > 0){                    
                    funcionesBanco.transferenciaCuenta(clienteBanco, txt_num_cuenta_origen.getText(), "O", montoTransferencia);
                    funcionesBanco.transferenciaCuenta(clienteBanco, txt_num_cuenta_destino.getText(), "D", montoTransferencia);
                    JOptionPane.showMessageDialog(null, "Transferencia exitosa", "Información", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                  JOptionPane.showMessageDialog(null, "Ingresar monto a transferir mayor a 0", "Advertencia", JOptionPane.OK_OPTION);  
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Ingresar valor numerico para transferir", "Advertencia", JOptionPane.OK_OPTION);
            }
            
        }
        
    }//GEN-LAST:event_btn_hacer_transferenciaActionPerformed

    private void txt_num_cuenta_origenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_num_cuenta_origenKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num_cuenta_origenKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_depositar;
    private javax.swing.JButton btn_girar;
    private javax.swing.JButton btn_hacer_deposito;
    private javax.swing.JButton btn_hacer_giro;
    private javax.swing.JButton btn_hacer_transferencia;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_nueva_transferencia;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_transferir;
    private javax.swing.JButton btn_validar_cuenta;
    private javax.swing.JButton btn_validar_rut;
    private javax.swing.JButton btn_validar_rut1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel jp_datos_cliente_giro;
    private javax.swing.JPanel jp_datos_deposito;
    private javax.swing.JPanel jp_datos_monto_dep;
    private javax.swing.JPanel jp_datos_transferencia;
    private javax.swing.JPanel jp_depositar;
    private javax.swing.JPanel jp_girar;
    private javax.swing.JPanel jp_saldo_giro;
    private javax.swing.JPanel jp_transferencia;
    private javax.swing.JPanel jp_transferencia_monto;
    private javax.swing.JLabel lb_ingrese_rut1;
    private javax.swing.JLabel lb_ingreso_rut;
    private javax.swing.JLabel lb_monto_transferencia;
    private javax.swing.JLabel lb_num_cuenta_destino;
    private javax.swing.JLabel lb_num_cuenta_origen;
    private javax.swing.JLabel lb_numeroCuenta;
    private javax.swing.JLabel lb_numero_cuenta_giro;
    private javax.swing.JLabel lb_saldoDisponible_giro;
    private javax.swing.JLabel lb_saldo_cuenta;
    private javax.swing.JLabel lb_saldo_deposito;
    private javax.swing.JLabel lb_saldo_giro;
    private javax.swing.JLabel lb_tipoCuenta;
    private javax.swing.JLabel lb_tipoCuenta_giro;
    private javax.swing.JTextField txt_ingreso_rut;
    private javax.swing.JTextField txt_ingreso_rut_giro;
    private javax.swing.JTextField txt_monto_transferencia;
    private javax.swing.JTextField txt_num_cuenta_destino;
    private javax.swing.JTextField txt_num_cuenta_origen;
    private javax.swing.JTextField txt_saldo_deposito;
    private javax.swing.JTextField txt_saldo_giro;
    // End of variables declaration//GEN-END:variables
}
